# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
#
# composer install
# php artisan key:generate
# npm install
# npm run dev
# php artisan serve
#

tasks:
  - init: composer install && npm install
    command: npm run dev && php artisan serve

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
